import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { ReactElement } from 'react';
import '../globals.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): ReactElement {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased flex justify-center`}>{children}</body>
    </html>
  );
}
